[2025-05-06 12:17:45.618] [posgeo_server] [info] === posgeo_server arrancando ===
[2025-05-06 12:17:45.619] [posgeo_server] [debug] Conectando a MongoDB en mongodb://localhost:28018
[2025-05-06 12:17:45.623] [posgeo_server] [critical] No se pudo hacer ping a MongoDB: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling hello on 'localhost:28018']: generic server error
[2025-05-06 12:18:01.467] [posgeo_server] [info] === posgeo_server arrancando ===
[2025-05-06 12:18:01.467] [posgeo_server] [debug] Conectando a MongoDB en mongodb://localhost:28018
[2025-05-06 12:18:01.469] [posgeo_server] [critical] No se pudo hacer ping a MongoDB: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling hello on 'localhost:28018']: generic server error
[2025-05-06 12:18:33.866] [posgeo_server] [info] === posgeo_server arrancando ===
[2025-05-06 12:18:33.867] [posgeo_server] [debug] Conectando a MongoDB en mongodb://localhost:28018
[2025-05-06 12:18:33.872] [posgeo_server] [info] Mongo ping response: { "ok" : 1.0 }
[2025-05-06 12:18:33.872] [posgeo_server] [info] HTTP servidor configurado en puerto 8080
[2025-05-06 12:18:33.873] [posgeo_server] [info] Servidor UDP escuchando en puerto 4000
[2025-05-06 12:18:33.873] [posgeo_server] [info] Servidor TCP escuchando en puerto 5000
[2025-05-06 12:18:33.873] [posgeo_server] [info] io_context.run() iniciado
[2025-05-06 12:18:54.083] [posgeo_server] [info] Endpoint /device → 3 dispositivos
[2025-05-06 12:19:35.322] [posgeo_server] [debug] UDP recibido (10 bytes): sinc
[2025-05-06 12:19:35.326] [posgeo_server] [info] UDP → insert_one OK
[2025-05-06 12:19:41.871] [posgeo_server] [info] Endpoint /device → 4 dispositivos
[2025-05-06 12:20:28.127] [posgeo_server] [info] Señal 2 recibida: deteniendo servicio...
[2025-05-06 12:20:28.128] [posgeo_server] [info] device_server finalizado correctamente
